from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILE_DIR = ROOT_DIR / 'files'
WINDOW_LOGO_PATH = FILE_DIR / 'logo.png'

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 20
SMALL_FONT_SIZE = 16
TEXT_MARGIN = 15
MiNIMUM_WIDTH = 250

# Colors
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'